web_app1/config/routes.rb
Rails.application.routes.draw do

  get 'card/new'
  get 'card/show'
  resources :orderhistories
  resources :orderlists
  resources :inquires
  get 'admin/index'
devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}
   get '/admin/index',to:'admin#index'
  root 'home#top'
  get '/',to: 'home#top'
  get '/about', to: 'home#about'
  
  get '/products/popular',to: 'products#popular'
  get '/products/side_dish',to: 'products#side_dish'
    get '/products/set_menu',to: 'products#set_menu'
 # post '/favorite/create',to: 'favorite#create'
 # delete '/favorite/destroy',to: 'favorite#destroy'
 # get '/favorite/index',to: 'favorite#index'
  
  post '/inquires/confirmation',to: 'inquires#confirmation'
  get '/inquires/complete',to: 'inquires#complete'
  
  get '/profiles/confirm',to: 'profiles#confirm'
  get '/profiles/:id/confirmate_delete',to: 'profiles#confirmate_delete',as: :confirmate_delete
  

  resources :carts,only:[:index,:create,:destroy]do
  collection do
    get 'destroy_all',to: 'carts#destroy_all'
  end
  end
  resources :profiles
  resources :products
  resources :inquires
  resources :admins,only:[:show]
  resources :users,only:[:show]
  resources :events
  
  resources :favorite

  
  
  resources :card, only: [:new, :show] do
  collection do
    get 'new',to: 'card#new'
    get 'orderform',to: 'card#orderform'
    post 'create', to: 'card#create'
    post 'show', to: 'card#show'
    post 'pay', to: 'card#pay'
    post 'delete', to: 'card#delete'
  end
end
end

web_app1/app/models/admin.rb
class Admin < ApplicationRecord
  has_many :eventpost
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

web_app1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

web_app1/app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user,optional: true
end

web_app1/app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

web_app1/app/models/eventpost.rb
class Eventpost < ApplicationRecord
  belongs_to :admin
  validates :title, presence: true
  validates :content, presence: true
end

web_app1/app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

web_app1/app/models/inquire.rb
class Inquire < ApplicationRecord
end

web_app1/app/models/orderhistory.rb
class Orderhistory < ApplicationRecord
  belongs_to :user
end

web_app1/app/models/orderlist.rb
class Orderlist < ApplicationRecord
  belongs_to :admin
  belongs_to :user
end

web_app1/app/models/product.rb
class Product < ApplicationRecord
    mount_uploaders :image, ImagesUploader
    acts_as_taggable
    has_many :favorites, dependent: :destroy
    has_many :cart, dependent: :destroy
    has_many :users, through: :favorites
    has_many :users,through: :carts

end

web_app1/app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  #validates :last_name, presence: true
end

web_app1/app/models/user.rb
class User < ApplicationRecord
    has_many :profiles,dependent: :destroy
    has_many :carts,dependent: :destroy
    has_many :favorites,dependent: :destroy
    has_many :orderhistories,dependent: :destroy
    has_many :cards,dependent: :destroy

    has_many :products, through: :favorites
    has_many :products,through: :carts
    #has_many :products,through: :orderhistories
    
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
         VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i
         validates :name, presence: true, length: { maximum: 50 }
         validates :email, presence: true, uniqueness: true,length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }
         validates :password, presence: true, length: { minimum: 7 }, format: { with: VALID_PASSWORD_REGEX }
end

web_app1/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  def index
    #binding.pry
    @products = Product.all.page(params[:page])
  end

  def popular
    @products = Product.all.page(params[:page])
  end

  def side_dish
       @products = Product.all.tagged_with(["惣菜","side_dish"],any: true).page(params[:page])

  end
  
  def set_menu
       @products = Product.all.tagged_with(["セット","セットメニュー","set"],any: true).page(params[:page])
  end
  # GET /products/1
  def show
 
puts @product.id
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
  @product.save
  redirect_to products_path
  end

  # PATCH/PUT /products/1
  def update
   @product.update(product_params)
    if @product.save!
     flash[:notice] = "投稿を編集しました"
     redirect_to products_path
    else
     render "edit"
  
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy
  redirect_to products_path
  end

 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find_by(id: params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :product_deta, :price,{image: []}, :tag_list)
    end
end

web_app1/app/helpers/admin_helper.rb
module AdminHelper
end

web_app1/app/helpers/card_helper.rb
module CardHelper
end

web_app1/app/helpers/carts_helper.rb
module CartsHelper
end

web_app1/app/helpers/events_helper.rb
module EventsHelper
end

web_app1/app/helpers/favorite_helper.rb
module FavoriteHelper
end

web_app1/app/helpers/home_helper.rb
module HomeHelper
end

web_app1/app/helpers/inquires_helper.rb
module InquiresHelper
end

web_app1/app/helpers/orderlists_helper.rb
module OrderlistsHelper
end

web_app1/app/helpers/products_helper.rb
module ProductsHelper
end

web_app1/app/helpers/profiles_helper.rb
module ProfilesHelper
end

web_app1/app/views/products/_form.html.erb
  <% @product.image[0..7].each do |image| %>
   <ul><%= image_tag image.url%></ul>
  <% end %>
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  


<div class="img_field">
  <%=form.label :image %>
  <%= form.file_field :image,multiple: true%>
      
      
  <div class="field">
    <%= form.label :name %></br>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :product_deta %></br>
    <%= form.text_area :product_deta %>
  </div>

  <div class="field">
    <%= form.label :price %></br>
    <%= form.text_field :price %>
  </div>
  <div class="field">
    <%= form.label :tag_list %>
    <%= text_field_tag 'product[tag_list]', product.tag_list, :class => "form-control" %>
  </div>
  <div >
    <%= form.submit '確定',class: 'btn btn-info btn-block',style: 'margin-top:5mm'%>
  </div>
<% end %>

web_app1/app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

web_app1/app/views/products/fish.html.erb
    <div class="row" style="margin-left: auto">
    <% @products.each do |product| %>
    <div class='card' style="width: 18rem;">
    <% if product.image.empty? %>
    <%= image_tag 'gray.jpg' %>    
    <%else%>
        <p ><%= image_tag product.image[0].url  %></p>
    <%end%>
        <h3><%= link_to product.name,product_path(product),class: 'card-title text-dark' %></h3>
        <p class='card-text '><%= product.price.to_s(:delimited) %>円</p>
        
        <% if admin_signed_in?%>
        <%= link_to '編集', edit_product_path(product),class: 'text-dark' %>
        <%= link_to '削除', product_path(product.id),class: 'text-dark',method: :delete, data: {comfirm: "削除してよろしいでしょうか?"} %>
        <% else %>
        <button type="button" class="btn btn-danger">カートに入れる</button>

      <%end%>
      </div>
    <% end %>
</div>
<%= paginate @products %>

web_app1/app/views/products/index.html.erb
 <% breadcrumb :products %>
 <%=  render "/layouts/breadcrumbs"%>
    
    <div class="row" style="margin-left: auto">
    <% @products.each do |product| %>
    <div class='card' style="width: 18rem;">
    <% if product.image.empty? %>
    <%= image_tag 'gray.jpg' %>    
    <%else%>
        <p ><%= image_tag product.image[0].url  %></p>
    <%end%>
        <h3><%= link_to product.name,product_path(product),class: 'card-title text-dark' %></h3>
        <p class='card-text '><%= product.price.to_s(:delimited) %>円</p>
        
        <% if admin_signed_in?%>
        <%= link_to '編集', edit_product_path(product),class: 'text-success' %>
        <%= link_to '削除', product_path(product.id),class: 'text-danger',method: :delete, data: {comfirm: "削除してよろしいでしょうか?"} %>
        <% else %>
        
          <%if Cart.exists?(user: current_user,product_id: product.id) %>
                <%= link_to 'カートから削除',cart_path(product.id),method: :delete,class: 'btn btn-secondary' %>
          <%else%>
                <%= link_to'カートに入れる',carts_path(id: product.id), method: :create,class: 'btn btn-danger'%>
          <%end%>

      <%end%>
      </div>
    <% end %>
</div>
<%= paginate @products %>

web_app1/app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to '<Back', products_path,class: 'btn btn-secondary' %>

web_app1/app/views/products/popular.html.erb
    <div class="row" style="margin-left: auto">
    <% @products.each do |product| %>
    <div class='card' style="width: 18rem;">
    <% if product.image.empty? %>
    <%= image_tag 'gray.jpg' %>    
    <%else%>
        <p ><%= image_tag product.image[0].url  %></p>
    <%end%>
        <h3><%= link_to product.name,product_path(product),class: 'card-title text-dark' %></h3>
        <p class='card-text '><%= product.price.to_s(:delimited) %>円</p>
        
        <% if admin_signed_in?%>
        <%= link_to '編集', edit_product_path(product),class: 'text-dark' %>
        <%= link_to '削除', product_path(product.id),class: 'text-dark',method: :delete, data: {comfirm: "削除してよろしいでしょうか?"} %>
        <% else %>
        <button type="button" class="btn btn-danger">カートに入れる</button>

      <%end%>
      </div>
    <% end %>
</div>
<%= paginate @products %>

web_app1/app/views/products/set_menu.html.erb
    <div class="row" style="margin-left: auto">
    <% @products.each do |product| %>
    <div class='card' style="width: 18rem;">
    <% if product.image.empty? %>
    <%= image_tag 'gray.jpg' %>    
    <%else%>
        <p ><%= image_tag product.image[0].url  %></p>
    <%end%>
        <h3><%= link_to product.name,product_path(product),class: 'card-title text-dark' %></h3>
        <p class='card-text '><%= product.price.to_s(:delimited) %>円</p>
        
        <% if admin_signed_in?%>
        <%= link_to '編集', edit_product_path(product),class: 'text-dark' %>
        <%= link_to '削除', product_path(product.id),class: 'text-dark',method: :delete, data: {comfirm: "削除してよろしいでしょうか?"} %>
        <% else %>
        <button type="button" class="btn btn-danger">カートに入れる</button>

      <%end%>
      </div>
    <% end %>
</div>
<%= paginate @products %>

web_app1/app/views/products/show.html.erb
 <% breadcrumb :product,@product %>
 <%=  render "/layouts/breadcrumbs"%>
<div class="row">
<%if @product.image.empty?%>
      
  <%= image_tag 'gray.jpg',class: 'img-thumbnail', alt: 'no image' ,width: '80'  %>

<%else%>
  <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
    <div class="carousel-inner">
         <div class="carousel-item active">
             <%= image_tag @product.image[0].url%>
          </div>
        <% @product.image[1..7].each do |image| %>
          <div class="carousel-item">
             <%= image_tag image.url%>
          </div>
     
        <% end %>
    
    </div>
  <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">前へ</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">次へ</span>
  </a>
</div>

<% end %>

  
<div class= "product-body">
  <p> <%= @product.product_deta %> </p>
</div>
</div>
<h3><%= @product.name %></h3>

  <p><%= @product.price.to_s(:delimited) %>円(税込み)</p>
  
<%if !admin_signed_in?%>
  <%if Cart.exists?(user: current_user, product_id: @product.id) %>
    <%= link_to 'カートから削除',cart_path(@product.id),method: :delete,class: 'btn btn-secondary' %>
  <%else%>
    <%= link_to'カートに入れる',carts_path(id: @product.id), method: :create,class: 'btn btn-danger'%>
  <%end%>
<%end%>

</br>
<%if Favorite.exists?(user: current_user, product_id: @product.id)%>
  <%= link_to 'お気に入りから削除',favorite_path(@product.id),method: :delete,class: 'btn btn-warning' %>

  <%else%>
    <%= link_to 'お気に入り追加',favorite_index_path(id: @product.id),method: :post ,class: 'btn btn-outline-warning'%>
<%end%>

<!-- 余裕があれば画像切り替えにJsを使う-->

web_app1/app/views/products/side_dish.html.erb
    <div class="row" style="margin-left: auto">
    <% @products.each do |product| %>
    <div class='card' style="width: 18rem;">
    <% if product.image.empty? %>
    <%= image_tag 'gray.jpg' %>    
    <%else%>
        <p ><%= image_tag product.image[0].url  %></p>
    <%end%>
        <h3><%= link_to product.name,product_path(product),class: 'card-title text-dark' %></h3>
        <p class='card-text '><%= product.price.to_s(:delimited) %>円</p>
        
        <% if admin_signed_in?%>
        <%= link_to '編集', edit_product_path(product),class: 'text-dark' %>
        <%= link_to '削除', product_path(product.id),class: 'text-dark',method: :delete, data: {comfirm: "削除してよろしいでしょうか?"} %>
        <% else %>
        <button type="button" class="btn btn-danger">カートに入れる</button>

      <%end%>
      </div>
    <% end %>
</div>
<%= paginate @products %>