web_app1/config/routes.rb
Rails.application.routes.draw do

  get 'card/new'
  get 'card/show'
  resources :orderhistories
  resources :orderlists
  resources :inquires
  get 'admin/index'
devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}
   get '/admin/index',to:'admin#index'
  root 'home#top'
  get '/',to: 'home#top'
  get '/about', to: 'home#about'
  
  get '/products/popular',to: 'products#popular'
  get '/products/side_dish',to: 'products#side_dish'
    get '/products/set_menu',to: 'products#set_menu'
 # post '/favorite/create',to: 'favorite#create'
 # delete '/favorite/destroy',to: 'favorite#destroy'
 # get '/favorite/index',to: 'favorite#index'
  
  post '/inquires/confirmation',to: 'inquires#confirmation'
  get '/inquires/complete',to: 'inquires#complete'
  
  get '/profiles/confirm',to: 'profiles#confirm'
  get '/profiles/:id/confirmate_delete',to: 'profiles#confirmate_delete',as: :confirmate_delete
  

  resources :carts,only:[:index,:create,:destroy]do
  collection do
    get 'destroy_all',to: 'carts#destroy_all'
  end
  end
  resources :profiles
  resources :products
  resources :inquires
  resources :admins,only:[:show]
  resources :users,only:[:show]
  resources :events
  
  resources :favorite

  
  
  resources :card, only: [:new, :show] do
  collection do
    get 'new',to: 'card#new'
    get 'orderform',to: 'card#orderform'
    post 'create', to: 'card#create'
    post 'show', to: 'card#show'
    post 'pay', to: 'card#pay'
    post 'delete', to: 'card#delete'
  end
end
end

web_app1/app/models/admin.rb
class Admin < ApplicationRecord
  has_many :eventpost
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

web_app1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

web_app1/app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user,optional: true
end

web_app1/app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

web_app1/app/models/eventpost.rb
class Eventpost < ApplicationRecord
  belongs_to :admin
  validates :title, presence: true
  validates :content, presence: true
end

web_app1/app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

web_app1/app/models/inquire.rb
class Inquire < ApplicationRecord
end

web_app1/app/models/orderhistory.rb
class Orderhistory < ApplicationRecord
  belongs_to :user
end

web_app1/app/models/orderlist.rb
class Orderlist < ApplicationRecord
  belongs_to :admin
  belongs_to :user
end

web_app1/app/models/product.rb
class Product < ApplicationRecord
    mount_uploaders :image, ImagesUploader
    acts_as_taggable
    has_many :favorites, dependent: :destroy
    has_many :cart, dependent: :destroy
    has_many :users, through: :favorites
    has_many :users,through: :carts

end

web_app1/app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  #validates :last_name, presence: true
end

web_app1/app/models/user.rb
class User < ApplicationRecord
    has_many :profiles,dependent: :destroy
    has_many :carts,dependent: :destroy
    has_many :favorites,dependent: :destroy
    has_many :orderhistories,dependent: :destroy
    has_many :cards,dependent: :destroy

    has_many :products, through: :favorites
    has_many :products,through: :carts
    #has_many :products,through: :orderhistories
    
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
         VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i
         validates :name, presence: true, length: { maximum: 50 }
         validates :email, presence: true, uniqueness: true,length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }
         validates :password, presence: true, length: { minimum: 7 }, format: { with: VALID_PASSWORD_REGEX }
end

web_app1/app/controllers/orderlists_controller.rb
class OrderlistsController < ApplicationController
  before_action :set_orderlist, only: [:show, :edit, :update, :destroy]

  # GET /orderlists
  # GET /orderlists.json
  def index
    
    @orderlists = Orderlist.all
  end

  # GET /orderlists/1
  # GET /orderlists/1.json
  def show
  end

  # GET /orderlists/new
  def new
    @orderlist = Orderlist.new
  end

  # GET /orderlists/1/edit
  def edit
  end

  # POST /orderlists
  # POST /orderlists.json
  def create
    @orderlist = Orderlist.new(orderlist_params)

    respond_to do |format|
      if @orderlist.save
        format.html { redirect_to @orderlist, notice: 'Orderlist was successfully created.' }
        format.json { render :show, status: :created, location: @orderlist }
      else
        format.html { render :new }
        format.json { render json: @orderlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orderlists/1
  # PATCH/PUT /orderlists/1.json
  def update
    respond_to do |format|
      if @orderlist.update(orderlist_params)
        format.html { redirect_to @orderlist, notice: 'Orderlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @orderlist }
      else
        format.html { render :edit }
        format.json { render json: @orderlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orderlists/1
  # DELETE /orderlists/1.json
  def destroy
    @orderlist.destroy
    respond_to do |format|
      format.html { redirect_to orderlists_url, notice: 'Orderlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orderlist
      @orderlist = Orderlist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def orderlist_params
      params.require(:orderlist).permit(:admin_id, :user_id, :product_items)
    end
end

web_app1/app/helpers/admin_helper.rb
module AdminHelper
end

web_app1/app/helpers/card_helper.rb
module CardHelper
end

web_app1/app/helpers/carts_helper.rb
module CartsHelper
end

web_app1/app/helpers/events_helper.rb
module EventsHelper
end

web_app1/app/helpers/favorite_helper.rb
module FavoriteHelper
end

web_app1/app/helpers/home_helper.rb
module HomeHelper
end

web_app1/app/helpers/inquires_helper.rb
module InquiresHelper
end

web_app1/app/helpers/orderlists_helper.rb
module OrderlistsHelper
end

web_app1/app/helpers/products_helper.rb
module ProductsHelper
end

web_app1/app/helpers/profiles_helper.rb
module ProfilesHelper
end

web_app1/app/views/orderlists/_form.html.erb
<%= form_with(model: orderlist, local: true) do |form| %>
  <% if orderlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(orderlist.errors.count, "error") %> prohibited this orderlist from being saved:</h2>

      <ul>
      <% orderlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :product_items %>
    <%= form.text_field :product_items %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

web_app1/app/views/orderlists/edit.html.erb
<h1>Editing Orderlist</h1>

<%= render 'form', orderlist: @orderlist %>

<%= link_to 'Show', @orderlist %> |
<%= link_to 'Back', orderlists_path %>

web_app1/app/views/orderlists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orderlists</h1>
    <% @orderlists.each do |orderlist| %>
      
        <%= orderlist.user.name %><br/>
        
        <%= orderlist.product_items.each do|items| %>
        <%=items%>
       
        <%end%>
       <br/> <%= link_to 'Show', orderlist %><br/>
        <%= link_to 'Edit', edit_orderlist_path(orderlist) %><br/>
        <%= link_to 'Destroy', orderlist, method: :delete, data: { confirm: 'Are you sure?' } %><br/>
      </tr>
    <% end %>
  </tbody>
</table>

web_app1/app/views/orderlists/new.html.erb
<h2>注文情報入力</h2>

<%= render 'form', orderlist: @orderlist %>

<%= link_to 'Back', orderlists_path %>

web_app1/app/views/orderlists/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>User:</strong>
  <%= @orderlist.user.name %>
</p>

<p>
  <strong>Product items:</strong>
  <%= @orderlist.product_items %>
</p>

<%= link_to 'Edit', edit_orderlist_path(@orderlist) %> |
<%= link_to 'Back', orderlists_path %>