web_app1/config/routes.rb
Rails.application.routes.draw do

  get 'card/new'
  get 'card/show'
  resources :orderhistories
  resources :orderlists
  resources :inquires
  get 'admin/index'
devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}
   get '/admin/index',to:'admin#index'
  root 'home#top'
  get '/',to: 'home#top'
  get '/about', to: 'home#about'
  
  get '/products/popular',to: 'products#popular'
  get '/products/side_dish',to: 'products#side_dish'
    get '/products/set_menu',to: 'products#set_menu'
 # post '/favorite/create',to: 'favorite#create'
 # delete '/favorite/destroy',to: 'favorite#destroy'
 # get '/favorite/index',to: 'favorite#index'
  
  post '/inquires/confirmation',to: 'inquires#confirmation'
  get '/inquires/complete',to: 'inquires#complete'
  
  get '/profiles/confirm',to: 'profiles#confirm'
  get '/profiles/:id/confirmate_delete',to: 'profiles#confirmate_delete',as: :confirmate_delete
  

  resources :carts,only:[:index,:create,:destroy]do
  collection do
    get 'destroy_all',to: 'carts#destroy_all'
  end
  end
  resources :profiles
  resources :products
  resources :inquires
  resources :admins,only:[:show]
  resources :users,only:[:show]
  resources :events
  
  resources :favorite

  
  
  resources :card, only: [:new, :show] do
  collection do
    get 'new',to: 'card#new'
    get 'orderform',to: 'card#orderform'
    post 'create', to: 'card#create'
    post 'show', to: 'card#show'
    post 'pay', to: 'card#pay'
    post 'delete', to: 'card#delete'
  end
end
end

web_app1/app/models/admin.rb
class Admin < ApplicationRecord
  has_many :eventpost
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

web_app1/app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user,optional: true
end

web_app1/app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

web_app1/app/models/eventpost.rb
class Eventpost < ApplicationRecord
  belongs_to :admin
  validates :title, presence: true
  validates :content, presence: true
end

web_app1/app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

web_app1/app/models/inquire.rb
class Inquire < ApplicationRecord
end

web_app1/app/models/orderhistory.rb
class Orderhistory < ApplicationRecord
  belongs_to :user
end

web_app1/app/models/orderlist.rb
class Orderlist < ApplicationRecord
  belongs_to :admin
  belongs_to :user
end

web_app1/app/models/product.rb
class Product < ApplicationRecord
    mount_uploaders :image, ImagesUploader
    acts_as_taggable
    has_many :favorites, dependent: :destroy
    has_many :cart, dependent: :destroy
    has_many :users, through: :favorites
    has_many :users,through: :carts

end

web_app1/app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  #validates :last_name, presence: true
end

web_app1/app/models/user.rb
class User < ApplicationRecord
    has_many :profiles,dependent: :destroy
    has_many :carts,dependent: :destroy
    has_many :favorites,dependent: :destroy
    has_many :orderhistories,dependent: :destroy
    has_many :cards,dependent: :destroy

    has_many :products, through: :favorites
    has_many :products,through: :carts
    #has_many :products,through: :orderhistories
    
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
         VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i
         validates :name, presence: true, length: { maximum: 50 }
         validates :email, presence: true, uniqueness: true,length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }
         validates :password, presence: true, length: { minimum: 7 }, format: { with: VALID_PASSWORD_REGEX }
end

web_app1/app/helpers/admin_helper.rb
module AdminHelper
end

web_app1/app/helpers/card_helper.rb
module CardHelper
end

web_app1/app/helpers/carts_helper.rb
module CartsHelper
end

web_app1/app/helpers/events_helper.rb
module EventsHelper
end

web_app1/app/helpers/favorite_helper.rb
module FavoriteHelper
end

web_app1/app/helpers/home_helper.rb
module HomeHelper
end

web_app1/app/helpers/inquires_helper.rb
module InquiresHelper
end

web_app1/app/helpers/products_helper.rb
module ProductsHelper
end

web_app1/app/helpers/profiles_helper.rb
module ProfilesHelper
end

web_app1/app/views/layouts/_breadcrumbs.html.erb
<div>
  <%= breadcrumbs separator: " &rsaquo; " %>
</div>

web_app1/app/views/layouts/_footer.html.erb
<footer class="border-top footer">
    <a>公式通販サイト燈庵</a><a>TEL:123-4321-5432</a>


<a class="background-color green">Copyright Rbs.Inc All Rights Reserved</a>
</footer>

web_app1/app/views/layouts/_header.html.erb
 <%= stylesheet_link_tag "home", :media => "all" %>
 <style>
.dropdown:hover > .dropdown-menu {
  display: block;
}
</style>
<header class ="border-bottom shadow-sm">
 <div>
<h1>燈庵</h1><p align="right">公式通販サイト燈庵 TEL:123-4321-5432</p>
          <nav  >
              <!-- admin log_in アクセス→topから'/admins/sign_in' 入力  -->
            <ul class="nav justify-content-end">
        <%if user_signed_in?%>
        <%= current_user.name%>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete,class: 'btn btn-link nav-item text-dark'%>|<li>
        <li><%= link_to 'お気に入り',favorite_index_path,class: 'btn btn-link nav-item text-dark'%>|</li>
        <li><%= link_to 'プロフィール',profiles_path,class: 'btn btn-link nav-item text-dark' %>|
        <li><%= link_to 'カート',carts_path,class: 'btn btn-link nav-item text-dark'%></li>
        <% elsif admin_signed_in? %>
        
        <li><%= link_to '管理者ページ', admin_index_path,class: 'btn btn-link nav-item text-dark'%>|<li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete,class: 'btn btn-link nav-item text-dark'%><li>

            <% else %>

        <li><%= link_to '会員登録', new_user_registration_path,class: 'btn btn-link nav-item text-dark'%>|</li>
          <li><%= link_to 'ログイン', new_user_session_path,class: 'btn btn-link nav-item text-dark'%>|</li>
          <li><%= link_to 'カート',root_path,class: 'btn btn-link nav-item text-dark'%></li>
          </ul>
          
          
          <% end %>
          </nav>
        <nav class="navi">

            <ul class="nav w-100 H-50 nav-justified justify-content-center ">
            <li class="btn nav-item"><%=link_to "TOP",root_path,class: 'nav-item text-success' %></li>
            
            <li class="nav-item dropdown">
            <a href="#" class=" nav-link dropdown-toggle text-success" id="navbarDropdown" 
            role="button"data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">商品リスト</a>
              
               <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                   
               <%= link_to "すべて",products_path,class: 'dropdown-item',data: {"turbolinks" => false}%>
               <%= link_to "人気","/products/popular",class: ' dropdown-item'%>
               <%= link_to "惣菜",products_side_dish_path,class: 'dropdown-item',data: {"turbolinks" => false}%>
               <%= link_to "セットメニュー",products_set_menu_path,class: 'dropdown-item',data: {"turbolinks" => false}%>
                <div class="dropdown-divider"></div>
               </div>
               
            </li>
            <li class="btn nav-item"><%=link_to "イベント",events_path,class: 'nav-item text-success' %></li>
            <li class="btn nav-item"><%=link_to "紹介", about_path,class: 'nav-item text-success'%></li>
            <li class="btn nav-item"><%=link_to "お問い合わせ", new_inquire_path,class: 'nav-item text-success' %></li>
            </ul>    
            
        </nav>


        <div>
</header>

web_app1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
          <script src= "https://js.pay.jp/"type="text/javascript"></script>

    <title>燈庵公式通販サイト</title>
    
  </head>

  <body>
    <%= render 'layouts/header' %>

    <%= yield %>
    <%= render 'layouts/footer' %>
           <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
  </body>
</html>